### PR TITLE
Adding a linting script

### PR DESCRIPTION
**Pull request by AnatoleLucet**
This PR is adding a script named `lint` which should regulate a bit the code base.

I think adding something like the following in the PR template could also help:
"Don't forget to run `yarn lint` before submitting your new pull request."

### CODE REVIEW

**Comment by benawad** [comment]
We should add a prettier config too

> I think adding something like the following in the PR template could also help:
How do I setup a PR template?

I'm going to add a bot that runs on each PR to make sure tests and linting passes

**Comment by AnatoleLucet** [comment]
@benawad don't you think `yarn lint --fix` is enough?

**Comment by benawad** [comment]
right now the eslint rules related to formatting conflict with prettier, so when I save the file it undoes the fix.

I want prettier to control they formatting and have eslint extend https://prettier.io/docs/en/integrating-with-linters.html#disable-formatting-rules

**Comment by AnatoleLucet** [comment]
@benawad alright, I haven't thought of that. I'm going to open a new PR.

**Pull request merged**
